/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */

#include "s3eExt.h"
#include "IwDebug.h"
#include "s3eDevice.h"


#include "admob.h"

/**
 * Definitions for functions types passed to/from s3eExt interface
 */
typedef  s3eResult(*admob_initSmart_t)(const char* pub_id, int orientation, int x, int y, int w, int h);
typedef  s3eResult(*admob_moveSmart_t)(int orientation, int x, int y, int w, int h);
typedef  s3eResult(*admob_init_t)(const char* pub_id, int ad_type, int orientation, int x, int y);
typedef  s3eResult(*admob_resize_t)(int ad_type);
typedef  s3eResult(*admob_show_t)();
typedef  s3eResult(*admob_refresh_t)();
typedef  s3eResult(*admob_hide_t)();
typedef  s3eResult(*admob_move_t)(int orientation, int x, int y);
typedef  s3eResult(*admob_interestial_preload_t)(const char * pub_id);
typedef       bool(*admob_interestial_isReady_t)();
typedef       bool(*admob_interestial_isShown_t)();
typedef       bool(*admob_interestial_wasShown_t)();
typedef       bool(*admob_interestial_hasBeenUsed_t)();
typedef  s3eResult(*admob_interestial_show_t)();
typedef  s3eResult(*admob_interestial_hide_t)();
typedef       bool(*admob_banner_isClicked_t)();
typedef       bool(*admob_interestial_isClicked_t)();

/**
 * struct that gets filled in by admobRegister
 */
typedef struct admobFuncs
{
    admob_initSmart_t m_admob_initSmart;
    admob_moveSmart_t m_admob_moveSmart;
    admob_init_t m_admob_init;
    admob_resize_t m_admob_resize;
    admob_show_t m_admob_show;
    admob_refresh_t m_admob_refresh;
    admob_hide_t m_admob_hide;
    admob_move_t m_admob_move;
    admob_interestial_preload_t m_admob_interestial_preload;
    admob_interestial_isReady_t m_admob_interestial_isReady;
    admob_interestial_isShown_t m_admob_interestial_isShown;
    admob_interestial_wasShown_t m_admob_interestial_wasShown;
    admob_interestial_hasBeenUsed_t m_admob_interestial_hasBeenUsed;
    admob_interestial_show_t m_admob_interestial_show;
    admob_interestial_hide_t m_admob_interestial_hide;
    admob_banner_isClicked_t m_admob_banner_isClicked;
    admob_interestial_isClicked_t m_admob_interestial_isClicked;
} admobFuncs;

static admobFuncs g_Ext;
static bool g_GotExt = false;
static bool g_TriedExt = false;
static bool g_TriedNoMsgExt = false;

static bool _extLoad()
{
    if (!g_GotExt && !g_TriedExt)
    {
        s3eResult res = s3eExtGetHash(0xf12fd48, &g_Ext, sizeof(g_Ext));
        if (res == S3E_RESULT_SUCCESS)
            g_GotExt = true;
        else
            s3eDebugAssertShow(S3E_MESSAGE_CONTINUE_STOP_IGNORE,                 "error loading extension: admob");
            
        g_TriedExt = true;
        g_TriedNoMsgExt = true;
    }

    return g_GotExt;
}

static bool _extLoadNoMsg()
{
    if (!g_GotExt && !g_TriedNoMsgExt)
    {
        s3eResult res = s3eExtGetHash(0xf12fd48, &g_Ext, sizeof(g_Ext));
        if (res == S3E_RESULT_SUCCESS)
            g_GotExt = true;
        g_TriedNoMsgExt = true;
        if (g_TriedExt)
            g_TriedExt = true;
    }

    return g_GotExt;
}

s3eBool admobAvailable()
{
    _extLoadNoMsg();
    return g_GotExt ? S3E_TRUE : S3E_FALSE;
}

s3eResult admob_initSmart(const char* pub_id, int orientation, int x, int y, int w, int h)
{
    IwTrace(ADMOB_VERBOSE, ("calling admob[0] func: admob_initSmart"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

#ifdef __mips
    // For MIPs platform we do not have asm code for stack switching 
    // implemented. So we make LoaderCallStart call manually to set GlobalLock
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    s3eResult ret = g_Ext.m_admob_initSmart(pub_id, orientation, x, y, w, h);

#ifdef __mips
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

s3eResult admob_moveSmart(int orientation, int x, int y, int w, int h)
{
    IwTrace(ADMOB_VERBOSE, ("calling admob[1] func: admob_moveSmart"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

#ifdef __mips
    // For MIPs platform we do not have asm code for stack switching 
    // implemented. So we make LoaderCallStart call manually to set GlobalLock
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    s3eResult ret = g_Ext.m_admob_moveSmart(orientation, x, y, w, h);

#ifdef __mips
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

s3eResult admob_init(const char* pub_id, int ad_type, int orientation, int x, int y)
{
    IwTrace(ADMOB_VERBOSE, ("calling admob[2] func: admob_init"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

#ifdef __mips
    // For MIPs platform we do not have asm code for stack switching 
    // implemented. So we make LoaderCallStart call manually to set GlobalLock
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    s3eResult ret = g_Ext.m_admob_init(pub_id, ad_type, orientation, x, y);

#ifdef __mips
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

s3eResult admob_resize(int ad_type)
{
    IwTrace(ADMOB_VERBOSE, ("calling admob[3] func: admob_resize"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

#ifdef __mips
    // For MIPs platform we do not have asm code for stack switching 
    // implemented. So we make LoaderCallStart call manually to set GlobalLock
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    s3eResult ret = g_Ext.m_admob_resize(ad_type);

#ifdef __mips
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

s3eResult admob_show()
{
    IwTrace(ADMOB_VERBOSE, ("calling admob[4] func: admob_show"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

#ifdef __mips
    // For MIPs platform we do not have asm code for stack switching 
    // implemented. So we make LoaderCallStart call manually to set GlobalLock
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    s3eResult ret = g_Ext.m_admob_show();

#ifdef __mips
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

s3eResult admob_refresh()
{
    IwTrace(ADMOB_VERBOSE, ("calling admob[5] func: admob_refresh"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

#ifdef __mips
    // For MIPs platform we do not have asm code for stack switching 
    // implemented. So we make LoaderCallStart call manually to set GlobalLock
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    s3eResult ret = g_Ext.m_admob_refresh();

#ifdef __mips
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

s3eResult admob_hide()
{
    IwTrace(ADMOB_VERBOSE, ("calling admob[6] func: admob_hide"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

#ifdef __mips
    // For MIPs platform we do not have asm code for stack switching 
    // implemented. So we make LoaderCallStart call manually to set GlobalLock
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    s3eResult ret = g_Ext.m_admob_hide();

#ifdef __mips
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

s3eResult admob_move(int orientation, int x, int y)
{
    IwTrace(ADMOB_VERBOSE, ("calling admob[7] func: admob_move"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

#ifdef __mips
    // For MIPs platform we do not have asm code for stack switching 
    // implemented. So we make LoaderCallStart call manually to set GlobalLock
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    s3eResult ret = g_Ext.m_admob_move(orientation, x, y);

#ifdef __mips
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

s3eResult admob_interestial_preload(const char * pub_id)
{
    IwTrace(ADMOB_VERBOSE, ("calling admob[8] func: admob_interestial_preload"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

#ifdef __mips
    // For MIPs platform we do not have asm code for stack switching 
    // implemented. So we make LoaderCallStart call manually to set GlobalLock
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    s3eResult ret = g_Ext.m_admob_interestial_preload(pub_id);

#ifdef __mips
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

bool admob_interestial_isReady()
{
    IwTrace(ADMOB_VERBOSE, ("calling admob[9] func: admob_interestial_isReady"));

    if (!_extLoad())
        return false;

#ifdef __mips
    // For MIPs platform we do not have asm code for stack switching 
    // implemented. So we make LoaderCallStart call manually to set GlobalLock
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    bool ret = g_Ext.m_admob_interestial_isReady();

#ifdef __mips
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

bool admob_interestial_isShown()
{
    IwTrace(ADMOB_VERBOSE, ("calling admob[10] func: admob_interestial_isShown"));

    if (!_extLoad())
        return false;

#ifdef __mips
    // For MIPs platform we do not have asm code for stack switching 
    // implemented. So we make LoaderCallStart call manually to set GlobalLock
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    bool ret = g_Ext.m_admob_interestial_isShown();

#ifdef __mips
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

bool admob_interestial_wasShown()
{
    IwTrace(ADMOB_VERBOSE, ("calling admob[11] func: admob_interestial_wasShown"));

    if (!_extLoad())
        return false;

#ifdef __mips
    // For MIPs platform we do not have asm code for stack switching 
    // implemented. So we make LoaderCallStart call manually to set GlobalLock
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    bool ret = g_Ext.m_admob_interestial_wasShown();

#ifdef __mips
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

bool admob_interestial_hasBeenUsed()
{
    IwTrace(ADMOB_VERBOSE, ("calling admob[12] func: admob_interestial_hasBeenUsed"));

    if (!_extLoad())
        return false;

#ifdef __mips
    // For MIPs platform we do not have asm code for stack switching 
    // implemented. So we make LoaderCallStart call manually to set GlobalLock
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    bool ret = g_Ext.m_admob_interestial_hasBeenUsed();

#ifdef __mips
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

s3eResult admob_interestial_show()
{
    IwTrace(ADMOB_VERBOSE, ("calling admob[13] func: admob_interestial_show"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

#ifdef __mips
    // For MIPs platform we do not have asm code for stack switching 
    // implemented. So we make LoaderCallStart call manually to set GlobalLock
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    s3eResult ret = g_Ext.m_admob_interestial_show();

#ifdef __mips
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

s3eResult admob_interestial_hide()
{
    IwTrace(ADMOB_VERBOSE, ("calling admob[14] func: admob_interestial_hide"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

#ifdef __mips
    // For MIPs platform we do not have asm code for stack switching 
    // implemented. So we make LoaderCallStart call manually to set GlobalLock
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    s3eResult ret = g_Ext.m_admob_interestial_hide();

#ifdef __mips
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

bool admob_banner_isClicked()
{
    IwTrace(ADMOB_VERBOSE, ("calling admob[15] func: admob_banner_isClicked"));

    if (!_extLoad())
        return false;

#ifdef __mips
    // For MIPs platform we do not have asm code for stack switching 
    // implemented. So we make LoaderCallStart call manually to set GlobalLock
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    bool ret = g_Ext.m_admob_banner_isClicked();

#ifdef __mips
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

bool admob_interestial_isClicked()
{
    IwTrace(ADMOB_VERBOSE, ("calling admob[16] func: admob_interestial_isClicked"));

    if (!_extLoad())
        return false;

#ifdef __mips
    // For MIPs platform we do not have asm code for stack switching 
    // implemented. So we make LoaderCallStart call manually to set GlobalLock
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    bool ret = g_Ext.m_admob_interestial_isClicked();

#ifdef __mips
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}
